[INFO     2012-10-04 08:03:34,812 bulkloader.py] Logging to bulkloader-log-20121004.080334
[INFO     2012-10-04 08:03:34,813 bulkloader.py] Throttling transfers:
[INFO     2012-10-04 08:03:34,813 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2012-10-04 08:03:34,813 bulkloader.py] HTTP connections: 8/second
[INFO     2012-10-04 08:03:34,813 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2012-10-04 08:03:34,813 bulkloader.py] Batch Size: 10
[INFO     2012-10-04 08:03:36,526 bulkloader.py] Opening database: bulkloader-progress-20121004.080334.sql3
[DEBUG    2012-10-04 08:03:36,588 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,589 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,589 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,589 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,590 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,590 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,591 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,591 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,591 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,592 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2012-10-04 08:03:36,592 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = localhost:8080
[DEBUG    2012-10-04 08:03:36,592 bulkloader.py] Bulkloader using app_id: dev~mycourse100
[INFO     2012-10-04 08:03:36,593 bulkloader.py] Connecting to localhost:8080/_ah/remote_api
[DEBUG    2012-10-04 08:03:36,611 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2012-10-04 08:03:36,611 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2012-10-04 08:03:36,612 bulkloader.py] Starting import; maximum 10 entities per post
[ERROR    2012-10-04 08:03:36,612 bulkloader.py] [Thread-12] DataSourceThread:
Traceback (most recent call last):
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 1579, in run
    self.PerformWork()
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 1698, in PerformWork
    for item in content_gen.Batches():
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 553, in Batches
    self._ReadRows(key_start, key_end)
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 463, in _ReadRows
    row = self.reader.next()
  File "/home/alex/hdd/progs/google_appengine/google/appengine/ext/bulkload/csv_connector.py", line 232, in generate_import_record
    % (line_number))
InvalidImportData: Got more values in row than headers on line 2.
[DEBUG    2012-10-04 08:03:36,613 bulkloader.py] [Thread-12] DataSourceThread: exiting
[INFO     2012-10-04 08:03:36,615 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2012-10-04 08:03:36,615 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,615 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,615 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,616 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,617 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: exiting
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,622 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2012-10-04 08:03:36,623 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2012-10-04 08:03:36,627 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2012-10-04 08:03:36,630 bulkloader.py] ... done.
[ERROR    2012-10-04 08:03:36,630 bulkloader.py] Error in data source thread: Got more values in row than headers on line 2.
[DEBUG    2012-10-04 08:03:36,630 bulkloader.py] Traceback (most recent call last):
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 1579, in run
    self.PerformWork()
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 1698, in PerformWork
    for item in content_gen.Batches():
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 553, in Batches
    self._ReadRows(key_start, key_end)
  File "/home/alex/hdd/progs/google_appengine/google/appengine/tools/bulkloader.py", line 463, in _ReadRows
    row = self.reader.next()
  File "/home/alex/hdd/progs/google_appengine/google/appengine/ext/bulkload/csv_connector.py", line 232, in generate_import_record
    % (line_number))
InvalidImportData: Got more values in row than headers on line 2.

[INFO     2012-10-04 08:03:36,631 bulkloader.py] 0 entities total, 0 previously transferred
[INFO     2012-10-04 08:03:36,631 bulkloader.py] 0 entities (534 bytes) transferred in 1.8 seconds
[INFO     2012-10-04 08:03:36,631 bulkloader.py] Some entities not successfully transferred
